### ISSUE TITLE
require the module returns an empty object

### ISSUE THREAD

**Issue by XVincentX** [jsumners/abstract-logging#2]
After the 2.0 upgrade, requiring the library returns an empty object instead of the logger.

**Comment by jsumners** [comment]
I added some extra tests in https://github.com/jsumners/abstract-logging/pull/3 and they verify cleanly. Can you post a script to replicate your issue?

**Comment by XVincentX** [comment]
Just a regular require statement

<img width="829" alt="image" src="https://user-images.githubusercontent.com/1416224/69129540-de657600-0aae-11ea-9615-692baa4b6189.png">

**Comment by jsumners** [comment]
The properties are not enumerable. Therefore they will not be shown in a serialization of the object.

**Comment by XVincentX** [comment]
I'll triple check, but basically I was getting a `info` is not a function in the code — maybe I did something wrong. Thanks for the clarification though.

**Comment by XVincentX** [comment]
For reference @jsumners: https://github.com/stoplightio/prism/pull/816

**Comment by jsumners** [comment]
Correction, the returned object "inherits" from the prototype where the methods are defined. So the methods are not "own properties" of the returned object. The net effect is the same: they will not be shown in serialization.

**Comment by jsumners** [comment]
> I'll triple check, but basically I was getting a info is not a function in the code

Is that your editor saying that? Or is this an actual runtime error? If it's an actual runtime error then that is why I am asking for a simple reproduction case. I am not seeing this in the test suite or anywhere else I am using the module.

**Comment by XVincentX** [comment]
It's a runtime error. Let me see if I can easily isolate it.

**Comment by jsumners** [comment]
@XVincentX have you been able to reproduce this?

**Comment by XVincentX** [comment]
This can be closed, I was having some problems with the `trace` method but it does not seem to be related to the library itself.
