### ISSUE TITLE
Add Typescript definitions file

### ISSUE THREAD

**Issue by piranna** [jsumners/abstract-logging#7]
Add `types.d.ts` file with definitions of the exported API.

**Comment by piranna** [comment]
Ok, fine if not planned, but I'm having typing issues by using `abstract-logging` to define a default logging value. I'm not an expert on Typescript, so how can I be able to define the exported value of this module? The alternative is to fully remove `abstract-logging` and make the logger required instead of optional on my code.

**Comment by jsumners** [comment]
I know nothing about TypeScript and will not be maintaining anything to do with TypeScript.
